#!/bin/sh
### BEGIN INIT INFO
# Provides:          extend-rootfs-once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

ROOT_PART="$(readlink -f /dev/disk/by-label/rootfs)"
DISK="/dev/$(lsblk -no pkname "$ROOT_PART")"

sudo growpart "$DISK" 2
sudo resize2fs "$ROOT_PART" >/dev/null 2>&1

rm /etc/init.d/extend-rootfs-once
